language: python

python: 
  - "3.4"
  - "3.5"

install: "pip install -r requirements.txt"
services: mongodb

before_script:
  - echo "TELEGRAM_TOKEN = '123456789:AABBCCDDEEFFGGHHJJKKLLMMNNOOPPRRSST';ADMINS_IDS = [ ];MODERS_IDS = [ ];DATABASE_PATH = 'db.json';USERS_PATH = 'users'" > config.py

script: "python tests.py"

after_success:
  - bash <(curl -s https://codecov.io/bash)